name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - development
      - release/**
      - hotfix/**
      - feature/**
  pull_request:
    branches:
      - main
      - development
      - release
      - hotfix
      - feature
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Gebruik de juiste versie voor MAUI
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui-android
 
      - name: Herstel afhankelijkheden
        run: dotnet restore
 
      - name: Bouw de applicatie
        run: dotnet build Grocery.App/Grocery.App.csproj --configuration Release --no-restore --framework net8.0-android /p:ApplicationId=nl.windesheim.groceryapp
 
      - name: Voer unit tests uit
        run: dotnet test Grocery.sln
